platforms:
  android:
    manifest:
      - file: AndroidManifest.xml
        target: manifest
        merge:
          <manifest>
            <uses-permission android:name="android.permission.CAMERA"/>
            <uses-permission android:name="android.Manifest.permission.RECORD_AUDIO"/>
            <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
            <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
          </manifest>